#
POST http://localhost:9000/api/datafaker/create-object
Content-Type: application/json

{
    "path": "/api/people",
    "name": "个人信息",
    "intro": "个人信息接口",
    "expression": {
        "fullname": "#{Name.full_name}", 
        "age": "#{number.number_between '15','50'}",
        "gender": "#{Gender.binaryTypes}",
        "address": {
            "city": "#{Address.city}",
            "street": "#{Address.streetAddress}",
            "zipCode": "#{Address.zipCode}"
        }
    }
}

###
POST http://localhost:9000/api/datafaker/create-array
Content-Type: application/json

{
    "path": "/api/people/list",
    "name": "所有个人信息",
    "intro": "所有个人信息接口",
    "expression": {
        "fullname": "#{Name.full_name}", 
        "age": "#{number.number_between '15','50'}",
        "gender": "#{Gender.binaryTypes}",
        "address": {
            "city": "#{Address.city}",
            "street": "#{Address.streetAddress}",
            "zipCode": "#{Address.zipCode}"
        }
    }
}

###
GET http://localhost:9000/api/datafaker/test-expression?text=%23{Name.full_name}

###
GET http://localhost:9000/api/datafaker/list

###
GET http://localhost:9000/api/people

###
GET http://localhost:9000/api/people/list?limit=5

###
GET http://localhost:9000/apife