### 创建个人信息接口
POST http://localhost:9000/api/datafaker/create-object
Content-Type: application/json

{
    "path": "/api/people",
    "name": "个人信息",
    "intro": "个人信息接口",
    "expression": {
        "fullname": "#{Name.full_name}", 
        "age": "#{number.number_between '15','50'}",
        "gender": "#{Gender.binaryTypes}",
        "address": {
            "city": "#{Address.city}",
            "street": "#{Address.streetAddress}",
            "zipCode": "#{Address.zipCode}"
        }
    }
}

### 查询个人信息接口
GET http://localhost:9000/api/people

### 创建所有个人信息接口
POST http://localhost:9000/api/datafaker/create-array
Content-Type: application/json

{
    "path": "/api/people/list",
    "name": "所有个人信息",
    "intro": "所有个人信息接口",
    "expression": {
        "fullname": "#{Name.full_name}", 
        "age": "#{number.number_between '15','50'}",
        "gender": "#{Gender.binaryTypes}",
        "address": {
            "city": "#{Address.city}",
            "street": "#{Address.streetAddress}",
            "zipCode": "#{Address.zipCode}"
        }
    }
}

### 查询所有个人信息接口
GET http://localhost:9000/api/people/list?limit=10

### 查询所有已创建的接口
GET http://localhost:9000/api/datafaker/list

### 测试 datafaker 表达式
GET http://localhost:9000/api/datafaker/test-expression?text=%23{Name.full_name}

###
GET http://localhost:9000/api/not-created